# Created by Nelson Durrant, Feb 2025
covariance_tuner:
  ros__parameters:
    # NOTE: The covariance defines how closely our EFK output follows the sensor data
    # A smaller covariance means the EFK will follow the sensor data more closely
    # A larger covariance means the EFK will follow the sensor data less closely
    odom_covariance_factor: 1.0
    gps_covariance_factor: 1.0
    imu_covariance_factor: 1.0
    # IMPORTANT! The default covariances (factor of 1.0) seem to do pretty well, be careful tuning them

imu_filter_madgwick: # combines IMU and magnetometer data from the ZED
  ros__parameters:
    use_mag: True
    use_magnetic_field_msg: True
    world_frame: 'enu' # to match robot_localization
    publish_tf: False
    publish_debug_topics: False

# ekf_filter_node_odom:
# The ZED calculates and manages the odom->zed_camera_link transform internally, and does a pretty good job
# https://www.stereolabs.com/docs/ros2/positional-tracking

ekf_filter_node_map: # outputs to the odometry/global topic
# This publishes the map->zed_camera_link transform
# https://robotics.stackexchange.com/questions/109942/odometry-with-robot-localization-using-gps-and-imu-not-encoders
  ros__parameters:
    frequency: 20.0 # The Jetson struggles to run faster than this
    two_d_mode: true  # Recommended to use 2d mode for nav2 in mostly planar environments
    print_diagnostics: false
    debug: false
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: zed_camera_link # base_footprint is used in Gazebo
    world_frame: map

    # https://docs.nav2.org/tutorials/docs/integrating_vio.html
    # https://www.stereolabs.com/docs/ros2/020_zed-node#published-topics
    odom0: zed/zed_node/odom_tuned # prefuses IMU data with VIO
    odom0_config: [true,  true,  false,  # X, Y, Z
                  false,  false,  true,  # Roll, Pitch, Yaw
                  false, false, false,   # Vx, Vy, Vz
                  false, false, false,   # Vroll, Vpitch, Vyaw
                  false, false, false]   # Ax, Ay, Az
    odom0_differential: true # Just fuse the differential change in position and orientation
    # odom0_relative: true # Redundant with differential
    odom0_queue_size: 2

    odom1: odometry/gps_tuned # from the navsat_transform_node
    odom1_config: [true,  true,  false,
                  false, false, false,
                  false, false, false,
                  false, false, false,
                  false, false, false]
    odom1_differential: false
    odom1_relative: false # We want to use the absolute GPS position
    odom1_queue_size: 2

    imu0: imu/data_tuned # from the madgwick filter
    imu0_config: [false, false, false,
                  false,  false,  true,
                  false, false, false,
                  false,  false,  false,
                  false,  false,  false]
    imu0_differential: false
    imu0_relative: false # We want to use the absolute IMU orientation
    imu0_queue_size: 2

    use_control: false # we could fuse in cmd_vel commands, but they are not very accurate

    # NOTE: We just use the built-in process noise covariance, and it seems to work well

navsat_transform:
  ros__parameters:
    frequency: 20.0 # The Jetson struggles to run faster than this
    delay: 3.0
    # https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml
    magnetic_declination_radians: 0.18814649 # in Provo
    yaw_offset: 0.0
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true # used by the path planners
    use_odometry_yaw: true
    wait_for_datum: false 
