# Created by Braden Meyers, Mar 2025
services:
  zed:
    image: zed_ros2_l4t_36.3.0_sdk_4.2.5
    container_name: zed-ct
    build: 
      context: .
      args:
        L4T_VERSION: l4t-r36.3.0
        ZED_SDK_MAJOR: 4
        ZED_SDK_MINOR: 2
        ZED_SDK_PATCH: 5
        L4T_MAJOR: 36
        L4T_MINOR: 3
    user: marsrover-zed
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      DISPLAY: ${DISPLAY} # Required for GUI applications
      QT_X11_NO_MITSHM: 1 # Required for GUI applications
    volumes:
      - ../../zed_ws:/home/marsrover-zed/zed_ws
      - ../../base_scripts/tmuxp/tmp:/home/marsrover-zed/.tmuxp
      - /usr/local/zed/resources/:/usr/local/zed/resources/
      - /usr/local/zed/settings/:/usr/local/zed/settings/
      - /dev:/dev:rw
      - /dev/shm:/dev/shm
      - /etc/udev:/etc/udev:rw
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /tmp/.X11-unix:/tmp/.X11-unix # Required for GUI applications
    stdin_open: true  # Equivalent to -it in docker run
    tty: true  # Equivalent to -it in docker run
    restart: always  # Keeps the container running after exit unless you want it to be removed like with --rm
    entrypoint: ["/bin/bash"]