# Waypoints for the SIMULATION environment
#
# NOTE: These parameters are parsed and loaded into the order planner in the action callback function.
# If you edit them, you'll need to kill the current action and request a new one using 'task_sim.sh'.
# You don't need to 'colcon build' the workspace after edits like with other config files.
waypoints:

# GPS waypoints (simulation)
# 1st waypoint (GPS only)
- leg: gps1
  latitude: 38.162923
  longitude: -122.454987
# 2nd waypoint (GPS only)
- leg: gps2
  latitude: 0.0
  longitude: 0.0

# Aruco tag waypoints (simulation)
# 3rd waypoint (Aruco tag)
- leg: aruco1
  latitude: 38.162958
  longitude: -122.455412
# 4th waypoint (Aruco tag)
- leg: aruco2
  latitude: 0.0
  longitude: 0.0
# 5th waypoint (Aruco tag)
- leg: aruco3
  latitude: 0.0
  longitude: 0.0

# Object waypoints (simulation)
# 6th waypoint (Mallet)
- leg: mallet
  latitude: 38.162635
  longitude: -122.454902
# 7th waypoint (Bottle)
- leg: bottle
  latitude: 0.0
  longitude: 0.0
