# Created by Nelson Durrant, Feb 2025
# Real waypoints for the rover to follow
waypoints:
# Start waypoint
- leg: start
  latitude: 0.0
  longitude: 0.0
  orig_wp: true
# 1st waypoint (GPS only)
- leg: gps1
  latitude: 0.0
  longitude: 0.0
  orig_wp: true
# 2nd waypoint (GPS only)
- leg: gps2
  latitude: 0.0
  longitude: 0.0
  orig_wp: true
# 3rd waypoint (Aruco)
- leg: aruco1
  latitude: 0.0
  longitude: 0.0
  orig_wp: true
  aruco_id: 0
# 4th waypoint (Aruco)
- leg: aruco2
  latitude: 0.0
  longitude: 0.0
  orig_wp: true
  aruco_id: 0
# 5th waypoint (Aruco)
- leg: aruco3
  latitude: 0.0
  longitude: 0.0
  orig_wp: true
  aruco_id: 0
# 6th waypoint (Mallet)
- leg: mallet
  latitude: 0.0
  longitude: 0.0
  orig_wp: true
# 7th waypoint (Bottle)
- leg: bottle
  latitude: 0.0
  longitude: 0.0
  orig_wp: true

waypoints:
# Start waypoint
- leg: start
  latitude: 38.161479 # Starting lat set in Gazebo world
  longitude: -122.454630 # Starting long set in Gazebo world
  orig_wp: true
# 1st waypoint (GPS only)
- leg: gps1
  latitude: 38.160891
  longitude: -122.453686
  orig_wp: true
# 2nd waypoint (GPS only)
- leg: gps2
  latitude: 38.160576
  longitude: -122.452829
  orig_wp: true
# 3rd waypoint (Aruco)
- leg: aruco1
  latitude: 38.161268
  longitude: -122.453233
  orig_wp: true
  aruco_id: 0
# 4th waypoint (Aruco)
- leg: aruco2
  latitude: 38.161801
  longitude: -122.454508
  orig_wp: true
  aruco_id: 0
# 5th waypoint (Aruco)
- leg: aruco3
  latitude: 38.162221
  longitude: -122.455083
  orig_wp: true
  aruco_id: 0
# 6th waypoint (Mallet)
- leg: mallet
  latitude: 38.162333
  longitude: -122.455990
  orig_wp: true
# 7th waypoint (Bottle)
- leg: bottle
  latitude: 38.161535
  longitude: -122.454720
  orig_wp: true

# TODO: Find a way to publish these on mapviz
