image_width: 1920
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1458.787516, 0, 1007.753867, 0, 1467.817809, 510.073189, 0, 0, 1]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.012038, 0.203487, -0.021023, 0.006009, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1, 0, 0, 0, 1, 0, 0, 0, 1]
projection_matrix:
  rows: 3
  cols: 4
  data: [1540.766235, 0, 1011.816434, 0, 0, 1536.717285, 489.014525, 0, 0, 0, 1, 0]
